spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'7
greeting-service:
  greeting: "Samuel xcar"
  default-value: "Mondo"